[package]
name = "token_examples"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-client = "2.1.13"
solana-sdk = "2.1.13"
solana-program = "2.1.13"
spl-token-2022 = "7.0.0"

anyhow = "1.0.95"
serde_json = "1.0.138"
dotenvy = "0.15.7"
spl-associated-token-account = "6.0.0"


